on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup dotnet 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: do test
        run: dotnet run build.cs -- --target Default --configuration Release
      - name: collect artifact
        uses: actions/upload-artifact@v6
        with:
          name: nuget-package
          path: artifacts/package/release/*.nupkg
